### ISSUE TITLE
Request App Package

### ISSUE THREAD

**Issue by gristy58** [Matej4386/SP2019-search#10]
Hey MateJ,
Are you able to provide a solution file i am having trouble building the solution and would like to try it out.

**Comment by Matej4386** [comment]
Hello,
I have put solution into release to try it out.

**Comment by softcloudservices** [comment]
> Hello,
> I have put solution into release to try it out.

Hi @Matej4386  i don't see  any   release folder in the solution can you please provide a link to the .sppkg file? i would like to test the solution.
Thanks,
Shiva

**Comment by Matej4386** [comment]
Heelo, link: https://github.com/Matej4386/SP2019-search/releases/download/2.0.0.6/my-search.sppkg

**Comment by softcloudservices** [comment]
> Hello, link: https://github.com/Matej4386/SP2019-search/releases/download/2.0.0.6/my-search.sppkg

Thanks, @Matej4386  for your quick response.
Thanks,
Shiva
