### ISSUE TITLE
Not working with anonymous access on SP2019?

### ISSUE THREAD

**Issue by hpreis** [Matej4386/SP2019-search#11]
Hello Matej, 

thank you very much for adopting the search webpart for SP2019.
The site collection where I use the 2019-search webpart is on a SP2019 server - a communication site which is activated for anonymous access. 
As long as I'm logged in the webpart works fine.
But when I'm logged of the webpart is loading and loading and loading.

Is there any chance to get the webpart running on an anonymous access site?

Kind regards
Harry

**Comment by Matej4386** [comment]
Hello @hpreis,
strange, I am really sorry but I do not have any option to test it on anonymous access site :-(.

**Comment by hpreis** [comment]
Hello @Matej4386,

I think in the HTTP POST besides the parameters ClientType, Querytext, ... it needs the parameter QueryTemplatePropertiesUrl for anonymous access ...

ClientType:	'PnPModernSearch'
Querytext: 'my search text'
QueryTemplatePropertiesUrl: 'spfile://webroot/queryparametertemplate.xml'

... please see the following articles ...

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview
https://www.eliostruyf.com/search-javascript-calls-not-working-for-anonymous-users-and-how-to-fix-it/
https://blog.mastykarz.nl/configuring-sharepoint-2013-search-rest-api-anonymous-users/
https://sharepoint.stackexchange.com/questions/159985/where-can-i-find-the-queryparametertemplate-xml-file

I would build an anonymous version for myself but struggle with the build and also with setting up the right components.

Is that right, that you used SPFx 1.4.1 for your WebPart?

https://tahoeninjas.blog/2019/12/30/spfx-compatibility-matrix/

and also this Versions or how did you setup build your WebPart for SP2019?
SPFx: 1.4.1
Node.js: LTS 6.x, LTS 8.x
NPM: v3, v4
TypeScript: V2.4
React: V15.x

Kind regards
Harry

**Comment by Matej4386** [comment]
Hello @hpreis,
thank you very much. I have used this config:
SPFx: 1.4.1
Node.js: 8.17.0
NPM: v6.13.4
TypeScript: V2.4.2
React: V15.6.2

For the part to extend anonymous access - yes it should be possible but i really do not have time now to update it. Really sorry.
