### ISSUE TITLE
Search Box for SP2019

### ISSUE THREAD

**Issue by DeveshRV** [Matej4386/SP2019-search#12]
Hi There, many thanks for this solution.

I am not sure how can we make use for Search box and other web parts for SP2019. Can you help on this

**Comment by DeveshRV** [comment]
Hello,

The search box and other webparts of original solution do not work with SharePoint 2019. Can you please integrate/ share links for the other webparts for SP2019. Many Thanks in advance

**Comment by Matej4386** [comment]
The solution is available here: https://github.com/Matej4386/SP2019-search/releases/tag/2.0.0.6

**Comment by Matej4386** [comment]
Hello,
sorry for late answer. What are the problems with package deployment?
Yes there is only one webpart (search box and search results are in 1 webpart because with spfx 1.4. we cant have 2 webparts communicating with each other).

Could you please post webpart settings?

**Comment by ManuSquall** [comment]
Hi  @Matej4386, hope you're doing well.

Thanks for the explanations, really helpfull.

Unfortunally, due to a local restriction situation, i can only deploy a webpart by enable "skipFeatureDeployment" property to true. I have tested your webpart by download it, add some change, bundle and package it again. 

Webpart screeshoots coming ahead:

**Comment by Matej4386** [comment]
Hi @ManuSquall skipFeatureDeployment property should not have any impact.

**Comment by ManuSquall** [comment]
Webpart screenshots:
![image](https://user-images.githubusercontent.com/29026887/144214914-49da969c-975a-47a1-bd70-ad2b825fe992.png)

Display of the webpart:
![image](https://user-images.githubusercontent.com/29026887/144216693-afb443d3-4420-4118-9a0c-4dcbd7940e6f.png)

Set " " (spacebar) for query keyword to display searchbar and results appear on the display:
![image](https://user-images.githubusercontent.com/29026887/144217109-b0c61dcf-4cf6-415f-850d-2f6e5782f2ec.png)

![image](https://user-images.githubusercontent.com/29026887/144215015-adb12a24-0a65-4fc2-b818-d0e91ecef5ea.png)

![image](https://user-images.githubusercontent.com/29026887/144217614-28d72a18-8c7e-4054-b56b-5b52be11cdc4.png)

![image](https://user-images.githubusercontent.com/29026887/144217650-8de0abbc-8232-4253-a2ab-af9734442d73.png)

![image](https://user-images.githubusercontent.com/29026887/144217715-9c9a43e5-59dd-409f-be18-f8838d741d0b.png)

![image](https://user-images.githubusercontent.com/29026887/144217782-4f1f54d4-2314-4232-8509-0566767fe1c3.png)

![image](https://user-images.githubusercontent.com/29026887/144217836-ef1bef80-8d50-4eae-8494-82af3fa2bf2c.png)

Beside all, is there a way to display the search bar without setting any query keywords?

Is it possible to add custom filter from a list basic column?

Do you also have so good links (or advice) on how to integrate search with KQL queries like what you have done ? :-)
Thank you for your time!

**Comment by Matej4386** [comment]
Hello, OK I have just tested it (fresh webaprt added to site). Yes at first there is no SearchBox (I think because of some props dont update well at start), I dont think you need to set up any query keywords, just go to the Search bar setting in properties pane and turn it of and on again.

**Comment by Matej4386** [comment]
![image](https://user-images.githubusercontent.com/58258968/144221824-bf0ff62e-f513-4a83-a193-ca873065c0ac.png)
![image](https://user-images.githubusercontent.com/58258968/144221873-c47c94d9-12a2-4868-a8b0-eb9c5b33b8dd.png)
![image](https://user-images.githubusercontent.com/58258968/144221951-1c4e6425-2936-4834-b47b-816d58c04507.png)
![image](https://user-images.githubusercontent.com/58258968/144221983-e2479260-310e-4475-98ee-bca3da775e96.png)
![image](https://user-images.githubusercontent.com/58258968/144222018-17b404fa-82a3-4875-8f4a-573f2c2a1973.png)

**Comment by Matej4386** [comment]
![image](https://user-images.githubusercontent.com/58258968/144222222-b3bd75ae-99a3-468b-9062-60649419739f.png)

**Comment by ManuSquall** [comment]
> Hello, OK I have just tested it (fresh webaprt added to site). Yes at first there is no SearchBox (I think because of some props dont update well at start), I dont think you need to set up any query keywords, just go to the Search bar setting in properties pane and turn it of and on again.

Have done it and it still not displaying. By the way it seems like your webpart settings display differ from mine. Is it possible to get his source code please? I'm actually using the webpart cod eof your master branch

**Comment by Matej4386** [comment]
Och sorry, I wasnt looking at this new version :-( my bad, I had two workbenchs running and old installed version on search in workbench. I modified code.

Small fix in src\webparts\nbsSearch\NbsSearchWebPart.ts:

if (isValueConnected && !this.properties.useDefaultSearchQuery ||
        isValueConnected && this.properties.useDefaultSearchQuery && this.properties.defaultSearchQuery ||
        !isValueConnected && !isEmpty(queryKeywords) **|| 
        this.properties.useSearchBox**) {
        renderElement = this._searchContainer;

**Comment by ManuSquall** [comment]
Thank you @Matej4386 🥳🥳

![image](https://user-images.githubusercontent.com/29026887/144413563-347f1bcb-0b41-47f6-8b6d-e36b00133b57.png)
