### ISSUE TITLE
Query to show People search results option in same template

### ISSUE THREAD

**Issue by DeveshRV** [Matej4386/SP2019-search#13]
Hello Matej,
Many Thanks for your great help!

We need your help in modifying the code for Search webpart in SP 2019.

Currently, we are able to search with a keyword and get the search result as per the Template selected in WebPart Properties(Ex. Slider, Details-List, Peoples, Tiles etc).
Now, We have a requirement to bring all the results and show on the Page like from Peoples & Documents in single search 'OR' We can provide a checkbox in the UI and show the search results based on the Checkbox value(Only People and Only Documents)

Appreciate your help for any suggestion or code sample.

**Comment by Matej4386** [comment]
Hello @DeveshRV,
thank you very much. I think the option B (Checkbox) should be easier, but I am really sorry I do not have time to provide sample.
I would go for the search box webpart - modified it to provide checkbox, then modify search props with checkbox_value which should be updated similar like search keywords from search box. After that modify search post request to handle checkbox_value to search only for documents or people.

**Comment by DeveshRV** [comment]
Hello Matej,

Thanks for your response.
We have tried this approach. However, we are facing some challenges in selecting the template dynamically (Resultlayoutoptions.People) in SearchResultContainer.ts as these values are set by default nbssearchwebpart.ts from page load/property pane configuration. 
Can you suggest how can we make these changes work dynamically?

**Comment by Matej4386** [comment]
Hello, maybe to create new state variable to handle selected temple.
