### ISSUE TITLE
How to use custom date range filter

### ISSUE THREAD

**Issue by DeveshRV** [Matej4386/SP2019-search#14]
Hi Matej,

Thanks for your support.
Requesting your kind help on how can we use custom date range refiner for search results. We have tried to apply it but the filter is not showing up. Something could be breaking

Is it related to custom managed property?
Appreciate your kind support

**Comment by Matej4386** [comment]
Hello,
please be more specific, what type is date column you want to filter, what does search result returns, is there any error or filter is just not showing?
