### ISSUE TITLE
Unable to select a specific site or list as data source

### ISSUE THREAD

**Issue by ManuSquall** [Matej4386/SP2019-search#15]
Hello @Matej4386, thanks a lot for the initiative and this webpart!
I'm facing some issues when i try to deploy it, instead of taking the sppkg that i can't deploy, i tried to package your solution with the "skipFeatureDeployment" parameter set to "true".
Once deployed i only see one webpart without the posibility to choose a data source list or site:

![image](https://user-images.githubusercontent.com/29026887/136248778-6bf2ab31-a6e5-4f71-b626-dfecf5e16a57.png)

And the search box is also missing if i don't check "Use a default search query" option with a default value:

![image](https://user-images.githubusercontent.com/29026887/136249232-7bd1d46b-e559-40eb-8b1b-7abc9c05425b.png)

Thanks in advance for anyone who can help me on those points or share some links.

**Comment by Matej4386** [comment]
Hello, sorry for late answer. To select data source or list you can use Query template property.

**Comment by ManuSquall** [comment]
Thanks @Matej4386, had to make some research on KQL to figure it out, never too late :-)
Thanks again to sharing this!

**Comment by Matej4386** [comment]
Your are welcome @ManuSquall. I am really happy that this can help someone. Yeah KQL is funny part of SharaPoint search :-)
