### ISSUE TITLE
SPPKG for SP2019

### ISSUE THREAD

**Issue by becko1001** [Matej4386/SP2019-search#19]
Hey Matej,

thanks for building this PnP-Webparts to SP 2019. This is exactly what I was looking for a long time.

Is there a possibility that you provide the solution as a Standard-Version as SPPKG-File? 
Unfortunately, I am not able to build the solution myself.

That would be mega, because I could use the functions very well!

Best regards,
becko1001

**Comment by Matej4386** [comment]
Hi @becko1001,
you can find .sppkg file in release - https://github.com/Matej4386/SP2019-search/releases/tag/2.0.0.6.

**Comment by becko1001** [comment]
I'm sorry! Thanks a lot!
