### ISSUE TITLE
Dynamic search in MySearch PnP webpart

### ISSUE THREAD

**Issue by shekhar0603** [Matej4386/SP2019-search#5]
Hello Matej,

Thank a lot for your contribution on PnP search webpart for SP2019.

I was working with the webpart and I have a query. 

Is the any option that we can make this dynamic ? As per scheenshot below we have to type in search box as shown :

![image](https://user-images.githubusercontent.com/39938835/113312924-635dd200-9328-11eb-87eb-a620d5d0942e.png)

@Matej4386 :Do we have any option where we can pass search item from querystring(same as pnp search webpart for SPOnline) to make this dynamic - www.xxxx/SitePages/SearchPage.aspx?k=Capacity ?

Regards,
Shekhar Chaudhary

**Comment by Matej4386** [comment]
Hello @shekhar0603,
thank you very much for your interest. I am very sorry but I really do not have any spare time to look at this now. I will be thinking about this. It is good update. Base on my knowledge the webpart does not handle this functionality.

**Comment by Matej4386** [comment]
Hello @shekhar0603 I have added quick change to NbsSearchWebPart.ts.

import { UrlHelper } from '../../../lib/helpers/UrlHelper';

in protected renderCompleted(): void {
after let queryKeywords = queryDataSourceValue ? queryDataSourceValue : this.properties.defaultSearchQuery;
put

const searchK: string = UrlHelper.getQueryStringParam('k', null);
    if (searchK) {
        queryKeywords = searchK;
    }

so if query will contain k param it will be used as search query for serach results webpart (and it will put k param in search box)

**Comment by shekhar0603** [comment]
Thanks @Matej4386 for this update. I think it will resolve my problem now.

**Comment by shekhar0603** [comment]
Hello @Matej4386 , above solution worked for me i.e using 'k' as search parameter.

But it only worked for single word : Ex : **?k=Capacity**

When I searched for multiple words using query string parameter i.e. : **?k=Capacity widget** , it didn't gave any search result.

So I tried using Search Box, it gave me results for **?k=Capacity widget.** as shown below:

![image](https://user-images.githubusercontent.com/39938835/114860856-2276ba80-9e0a-11eb-8969-92c11b5c7398.png)

Also query string is not working for any Boolean operator but search box is working ex:  **?k=Capacity NEAR filters.**

![image](https://user-images.githubusercontent.com/39938835/114861300-b0eb3c00-9e0a-11eb-8fae-478a2c55a093.png)

If you can please look into this issue and make **Boolean operator** and **multiple words** to be searched using query string work.

Thanks,
Shekhar
